# Generated by Django 4.2.4 on 2023-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
    ]
