# Generated by Django 4.2.4 on 2023-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0004_product_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(default='', upload_to='products/')),
                ('product_model', models.CharField(max_length=30)),
                ('product_ram', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product_mst',
            old_name='pname',
            new_name='pbrand',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
