# Generated by Django 4.2.4 on 2023-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0005_product_sub_cat_rename_pname_product_mst_pbrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mst',
            name='p_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
