# Generated by Django 4.2.4 on 2023-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0007_rename_p_name_product_mst_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sub_cat',
            name='product_image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product_sub_cat',
            name='product_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_sub_cat',
            name='product_ram',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
