#string demo built inn fuction 
st="Tops Technologies"

print(st)
print(st.capitalize())
print(st.casefold())
print(st.lower())
print(st.upper())
print(st.center(40,"$"))
print(st.count("T"))
print(st.endswith("es"))
print(st.startswith("To"))
print(st.find("log"))
print(st.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print(st.istitle())
print("tops".islower())
print("TOPS".isupper())
print("hello".replace("l","w"))
print(st.swapcase())
